USERNAME_INPUT = "input[name=username]"
PASSWORD_INPUT = "input[name=password]"
SUBMIT_CREDENTIALS_BUTTON = "button[type=submit]"
ALLOW_COOKIES_BUTTON = "body > div.RnEpo.Yx5HN._4Yzd2 > div > div > button.aOOlW.HoLwm"
DONT_SAVE_PASSWORD_BUTTON = "#react-root > section > main > div > div > div > div > button"
DONT_TURN_ON_NOTIFICATIONS_BUTTON = "body > div.RnEpo.Yx5HN > div > div > div > div.mt3GC > button.aOOlW.HoLwm"
POST = "#react-root > section > main > div > div.ltEKP > article > div > div._97aPb.wKWK0 > div > div > div._9AhH0"
MORE_OPTIONS_BUTTON = "svg[aria-label='More options']"
REPORT_BUTTON= "body > div.RnEpo.Yx5HN > div > div > div > div > button.aOOlW.-Cab_"
FALSE_INFORMATION = "body > div.RnEpo.Yx5HN > div > div > div > div.jIHp4 > div > div > div > div.J09pf > button:nth-child(11) > div > div.qF0y9.Igw0E.IwRSH.eGOV_.vwCYk"
POLITICS_REASON = "//div[text()='Politics']"
CLOSE_BUTTON = "body > div.RnEpo.Yx5HN > div > div > div > div > div > div > div.qF0y9.Igw0E.IwRSH.eGOV_._4EzTm.MGdpg.aGBdT.XfCBB > button"