BASE_PATH = "https://www.instagram.com/"

RELOAD_BUTTON = "reload-button"
USERNAME_INPUT = "input[name=username]"
PASSWORD_INPUT = "input[name=password]"
SUBMIT_CREDENTIALS_BUTTON = "button[type=submit]"
LOCK = "//h1[text()='Instagram']"
ALLOW_COOKIES_BUTTON = "body > div.RnEpo.Yx5HN._4Yzd2 > div > div > button.aOOlW.HoLwm"
DONT_SAVE_PASSWORD_BUTTON = "#react-root > section > main > div > div > div > div > button"
DONT_TURN_ON_NOTIFICATIONS_BUTTON = "//button[text()='Not Now']"
FOLLOW_BUTTON = "//div[text()='Follow']"
AFTER_FOLLOW = "span[aria-label=Following]"
UNFOLLOW_BUTTON = "//button[text()='Unfollow']"
MORE_OPTIONS_BUTTON_POST = "svg[aria-label='More options']"
MORE_OPTIONS_BUTTON_USER = "svg[aria-label='Options']"
REPORT_BUTTON = "//button[text()='Report']"
REPORT_ACCOUNT_BUTTON = "//div[text()='Report Account']"
REASON_BUTTON = "svg[aria-label='chevron']"
FALSE_INFORMATION = "//div[text()='False information']"
POLITICS_REASON = "//div[text()='Politics']"
CLOSE_BUTTON = "body > div.RnEpo.Yx5HN > div > div > div > div > div > div > div.qF0y9.Igw0E.IwRSH.eGOV_._4EzTm.MGdpg.aGBdT.XfCBB > button"
